#!/bin/sh
start_time=$SECONDS

#color codes, ALWAYS END WITH ESCAPE
red='\x1B[0;31m'
green='\x1B[0;32m'
blue='\x1B[0;34m'
white='\x1B[0;37m'
escape='\x1B[0m'

#show responses for commands
showResponses() {
  #check if it exited cleanly or threw errors
  if [[ "$1" -eq 0 ]]; then
    printf "$green done $escape \n"
  else
    printf "$red failed $escape \n"
    #something went wrong, exit with error
    exit 1
  fi
}

if screen -list | grep -q "borrow-bot"; then
  # docker is already running, let's stop this script
  printf "$white BorrowBot is already running! Shutting down...$escape\n"
  screen -S borrow-bot -X quit &> /dev/null
  showResponses $?
fi

# installing
printf "$white Running NPM install...$escape\n"
npm install &> /dev/null
showResponses $?

# copying config
printf "$white Copying config file...$escape\n"
cp ../../../config.json ./config.json &> /dev/null
showResponses $?

# starting up the screen
printf "$white Starting up BorrowBot...$escape\n"
screen -S borrow-bot -d -m npm start &> /dev/null
showResponses $?

elapsed_time=$(($SECONDS - $start_time))
printf "$white\n"
printf "Install was completed$green successfully$white in $blue$elapsed_time seconds$white!$escape\n"
# nothing went wrong, exit cleanly
exit 0
